SOURCES=\
	arbre-binari/red-black-tree.c \
	linked-list/linked-list.c

FILES_C = practica2.c red-black-tree.c linked-list.c

TARGET = practica2

LFLAGS = -lm

FILES_O =$(subst .c,.o,$(FILES_C))

$(TARGET): $(FILES_O) Makefile
	gcc $(FILES_O) -o $(TARGET) $(LFLAGS)

clean:
	/bin/rm $(FILES_O) $(TARGET) 
